// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type GlAccount struct {
	Account       int32          `json:"account"`
	Child         int32          `json:"child"`
	ParentAccount sql.NullBool   `json:"parent_account"`
	Type          sql.NullString `json:"type"`
	SubType       sql.NullString `json:"sub_type"`
	Description   sql.NullString `json:"description"`
	Balance       sql.NullString `json:"balance"`
	Comments      sql.NullString `json:"comments"`
	CreateDate    sql.NullTime   `json:"create_date"`
	CreateUser    sql.NullString `json:"create_user"`
	UpdateDate    sql.NullTime   `json:"update_date"`
	UpdateUser    sql.NullString `json:"update_user"`
}

type GlAccountType struct {
	Type        string         `json:"type"`
	Description sql.NullString `json:"description"`
	CreateDate  sql.NullTime   `json:"create_date"`
	CreateUser  sql.NullString `json:"create_user"`
	UpdateDate  sql.NullTime   `json:"update_date"`
	UpdateUser  sql.NullString `json:"update_user"`
}

type GlDistribution struct {
	DistParentID int32          `json:"dist_parent_id"`
	DistChildID  int32          `json:"dist_child_id"`
	JournalID    sql.NullInt32  `json:"journal_id"`
	JournalSubid sql.NullInt32  `json:"journal_subid"`
	CreatedDate  sql.NullTime   `json:"created_date"`
	UpdateDate   sql.NullTime   `json:"update_date"`
	CreatedUser  sql.NullString `json:"created_user"`
}

type GlDistributionLedger struct {
	Account        int32          `json:"account"`
	Child          int32          `json:"child"`
	Period         int32          `json:"period"`
	Description    sql.NullString `json:"description"`
	OpeningBalance string         `json:"opening_balance"`
	DebitBalance   string         `json:"debit_balance"`
	CreditBalance  string         `json:"credit_balance"`
	ClosingBalance string         `json:"closing_balance"`
	UpdateDate     sql.NullTime   `json:"update_date"`
	CreatedUser    sql.NullString `json:"created_user"`
}

type GlJournalDetail struct {
	JournalID    int32          `json:"journal_id"`
	JournalSubid int32          `json:"journal_subid"`
	Account      sql.NullInt32  `json:"account"`
	Child        sql.NullInt32  `json:"child"`
	SubType      sql.NullString `json:"sub_type"`
	Description  sql.NullString `json:"description"`
	Debit        sql.NullString `json:"debit"`
	Credit       sql.NullString `json:"credit"`
	CreateDate   sql.NullTime   `json:"create_date"`
	CreateUser   sql.NullString `json:"create_user"`
}

type GlJournalHeader struct {
	JournalID   int32          `json:"journal_id"`
	Description sql.NullString `json:"description"`
	Booked      sql.NullBool   `json:"booked"`
	BookedDate  sql.NullTime   `json:"booked_date"`
	BookedUser  sql.NullString `json:"booked_user"`
	CreateDate  sql.NullTime   `json:"create_date"`
	CreateUser  sql.NullString `json:"create_user"`
	// Period for the transaction
	Period sql.NullInt32 `json:"period"`
}

type GlPeriod struct {
	PeriodID    int32          `json:"period_id"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Description sql.NullString `json:"description"`
	CreateDate  sql.NullTime   `json:"create_date"`
	CreateUser  sql.NullString `json:"create_user"`
	UpdateDate  sql.NullTime   `json:"update_date"`
	UpdateUser  sql.NullString `json:"update_user"`
}

type GlTrialBalance struct {
	Account            string         `json:"account"`
	Child              string         `json:"child"`
	StartDate          sql.NullTime   `json:"start_date"`
	EndDate            sql.NullTime   `json:"end_date"`
	AccountingPeriodID sql.NullInt32  `json:"accounting_period_id"`
	Description        sql.NullString `json:"description"`
	Type               sql.NullString `json:"type"`
	Debit              sql.NullString `json:"debit"`
	Credit             sql.NullString `json:"credit"`
	CreateDate         sql.NullTime   `json:"create_date"`
	CreateUser         sql.NullString `json:"create_user"`
	UpdateDate         sql.NullTime   `json:"update_date"`
	UpdateUser         sql.NullString `json:"update_user"`
}

type KbPriority struct {
	Priority    string         `json:"priority"`
	Description sql.NullString `json:"description"`
	Updatedte   sql.NullTime   `json:"updatedte"`
	Updateusr   sql.NullString `json:"updateusr"`
}

type KbStatus struct {
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
	Updatedte   sql.NullTime   `json:"updatedte"`
	Updateusr   sql.NullString `json:"updateusr"`
}

type KbSubtask struct {
	TaskID   string         `json:"task_id"`
	Subid    string         `json:"subid"`
	Desc     sql.NullString `json:"desc"`
	Status   sql.NullString `json:"status"`
	Summary  sql.NullString `json:"summary"`
	Type     sql.NullString `json:"type"`
	Estimate sql.NullInt32  `json:"estimate"`
}

type KbTask struct {
	TaskID       string         `json:"task_id"`
	PartyRef     sql.NullString `json:"party_ref"`
	Title        sql.NullString `json:"title"`
	Status       sql.NullString `json:"status"`
	Summary      sql.NullString `json:"summary"`
	Type         sql.NullString `json:"type"`
	Priority     sql.NullString `json:"priority"`
	Tags         sql.NullString `json:"tags"`
	Estimate     sql.NullInt32  `json:"estimate"`
	Assignee     sql.NullString `json:"assignee"`
	Rankid       sql.NullInt32  `json:"rankid"`
	Color        sql.NullString `json:"color"`
	Classname    sql.NullString `json:"classname"`
	Id           sql.NullInt32  `json:"Id"`
	Dependencies sql.NullString `json:"dependencies"`
	Description  sql.NullString `json:"description"`
	DueDate      sql.NullTime   `json:"due_date"`
	ParentId     sql.NullInt32  `json:"parentId"`
	StartDate    sql.NullTime   `json:"start_date"`
}

type KbTeam struct {
	TeamMember string         `json:"team_member"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Location   sql.NullString `json:"location"`
	Title      sql.NullString `json:"title"`
	Updatedte  sql.NullTime   `json:"updatedte"`
	Updateusr  sql.NullString `json:"updateusr"`
}

type KbType struct {
	Type        string         `json:"type"`
	Description sql.NullString `json:"description"`
	Updatedte   sql.NullTime   `json:"updatedte"`
	Updateusr   sql.NullString `json:"updateusr"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
