// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListDistLedger(ctx context.Context) ([]GlDistributionLedger, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	getDistLedgerByRef(ctx context.Context, arg getDistLedgerByRefParams) (GlDistributionLedger, error)
}

var _ Querier = (*Queries)(nil)
