// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateInstExt(ctx context.Context, arg CreateInstExtParams) (TrdInstExt, error)
	CreateInstructionEffect(ctx context.Context, arg CreateInstructionEffectParams) (TrdInstructionEffect, error)
	CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (TrdInstrument, error)
	CreateJournal(ctx context.Context, arg CreateJournalParams) (TrdJournal, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (TrdLink, error)
	CreateParty(ctx context.Context, arg CreatePartyParams) (TrdParty, error)
	CreatePartyDriver(ctx context.Context, arg CreatePartyDriverParams) (TrdPartyDriver, error)
	CreateProcessing(ctx context.Context, arg CreateProcessingParams) (TrdProcessing, error)
	CreateProcessingEvent(ctx context.Context, arg CreateProcessingEventParams) (TrdProcessingEvent, error)
	CreateRate(ctx context.Context, arg CreateRateParams) (TrdRate, error)
	CreateRefDate(ctx context.Context, arg CreateRefDateParams) (TrdRefDate, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (TrdSettlement, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (TrdTrade, error)
	CreateTradeNarrative(ctx context.Context, arg CreateTradeNarrativeParams) (TrdTradeNarrative, error)
	CreateTradeOne(ctx context.Context, arg CreateTradeOneParams) (TrdTradeCode, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateTrdAmount(ctx context.Context, arg CreateTrdAmountParams) (TrdAmount, error)
	CreateTrdDriver(ctx context.Context, arg CreateTrdDriverParams) (TrdDriver, error)
	CreateTrdEvent(ctx context.Context, arg CreateTrdEventParams) (TrdEvent, error)
	CreateTrdEventNarrative(ctx context.Context, arg CreateTrdEventNarrativeParams) (TrdEventNarrative, error)
	CreateTrdExternalRef(ctx context.Context, arg CreateTrdExternalRefParams) (TrdExternalRef, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTrade(ctx context.Context, trdRecordno int32) (TrdTrade, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListAllTrades(ctx context.Context) ([]TrdTrade, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListInstruments(ctx context.Context) ([]InstrInstrument, error)
	ListParties(ctx context.Context) ([]PtyParty, error)
	ListTradeAmount(ctx context.Context) ([]TrdAmount, error)
	ListTradeCode(ctx context.Context, trdRecordno int32) ([]TrdTradeCode, error)
	ListTradeDriver(ctx context.Context, trdRecordno int32) ([]TrdDriver, error)
	ListTradeEvent(ctx context.Context, trdRecordno int32) ([]TrdEvent, error)
	ListTradeEventNarrative(ctx context.Context, trdRecordno int32) ([]TrdEventNarrative, error)
	ListTradeExternalRef(ctx context.Context, trdRecordno int32) ([]TrdExternalRef, error)
	ListTradeInstExt(ctx context.Context, trdRecordno int32) ([]TrdInstExt, error)
	ListTradeInstruction(ctx context.Context, trdRecordno int32) ([]TrdInstruction, error)
	ListTradeInstructionEffect(ctx context.Context, trdRecordno int32) ([]TrdInstructionEffect, error)
	ListTradeInstrument(ctx context.Context, trdRecordno int32) ([]TrdInstrument, error)
	ListTradeJournal(ctx context.Context, trdRecordno int32) ([]TrdJournal, error)
	ListTradeLink(ctx context.Context, trdRecordno int32) ([]TrdLink, error)
	ListTradeNarrative(ctx context.Context, trdRecordno int32) ([]TrdTradeNarrative, error)
	ListTradeParty(ctx context.Context, trdRecordno int32) ([]TrdParty, error)
	ListTradePartyDriver(ctx context.Context, trdRecordno int32) ([]TrdPartyDriver, error)
	ListTradeProcessing(ctx context.Context, trdRecordno int32) ([]TrdProcessing, error)
	ListTradeProcessingEvent(ctx context.Context, trdRecordno int32) ([]TrdProcessingEvent, error)
	ListTradeRate(ctx context.Context, trdRecordno int32) ([]TrdRate, error)
	ListTradeRefDate(ctx context.Context, trdRecordno int32) ([]TrdRefDate, error)
	ListTradeSettlement(ctx context.Context, trdRecordno int32) ([]TrdSettlement, error)
	ListTrades(ctx context.Context, arg ListTradesParams) ([]TrdTrade, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
