Table "accounts" {
  "id" bigint [not null]
  "owner" "character varying" [not null]
  "balance" bigint [not null]
  "currency" "character varying" [not null]
  "created_at" timestamp [not null, default: `now()`]
}

Table "entries" {
  "id" bigint [not null]
  "account_id" bigint [not null]
  "amount" bigint [not null]
  "created_at" timestamp [not null, default: `now()`]
}

Table "instr_instruments" {
  "instr_instref" text [not null]
  "instr_instgrp" text [not null]
  "instr_longdesc" text [not null]
  "instr_denminst" text [not null]
  "instr_pricedps" text [not null]
  "instr_divisor" text [not null]
  "instr_multiplier" text [not null]
  "instr_pricetype" text [not null]
  "instr_tick" text [not null]
  "instr_accrued" text [not null]
  "instr_minqty" text [not null]
  "instr_qtydps" text [not null]
  "instr_shrtdesc" text [not null]
  "instr_market" text [not null]
  "instr_settinst" text [not null]
  "instr_book" text [not null]
  "instr_maxmovt" text [not null]
  "instr_minmovt" text [not null]
  "instr_active" text [not null]
  "instr_verdat" text [not null]
}

Table "pty_party" {
  "pty_partyref" text [not null]
  "pty_category" text [not null]
  "pty_longdesc" text [not null]
  "pty_holiday" text [not null]
  "pty_country" text [not null]
  "pty_location" text [not null]
  "pty_shrtdesc" text [not null]
  "pty_partynam1" text [not null]
  "pty_partynam2" text [not null]
  "pty_partynam3" text [not null]
  "pty_active" text [not null]
  "pty_verdat" text [not null]
}

Table "schema_migrations" {
  "version" bigint [not null]
  "dirty" boolean [not null]
}

Table "sessions" {
  "id" uuid [not null]
  "username" "character varying" [not null]
  "refresh_token" "character varying" [not null]
  "user_agent" "character varying" [not null]
  "client_ip" "character varying" [not null]
  "is_blocked" boolean [not null, default: false]
  "expires_at" timestamp [not null]
  "created_at" timestamp [not null, default: `now()`]
}

Table "transfers" {
  "id" bigint [not null]
  "from_account_id" bigint [not null]
  "to_account_id" bigint [not null]
  "amount" bigint [not null, note: 'must be positive']
  "created_at" timestamp [not null, default: `now()`]
}

Table "trd_amount" {
  "trd_recordno" integer [not null]
  "trd_charge_levy_type_p2k" text [not null]
  "trd_charge_levy_instr_p2k" text [not null]
  "trd_charge_discount_wil" text [not null]
  "trd_charge_levy_qty_p2k" text [not null]
  "trd_charge_levyrate_p2k" text [not null]
}

Table "trd_driver" {
  "trd_recordno" integer [not null]
  "trd_drivertype" text [not null]
  "trd_drivercode" text [not null]
}

Table "trd_event" {
  "trd_recordno" integer [not null]
  "trd_eventtype" text [not null]
  "trd_eventdate" text [not null]
  "trd_eventdateto" text [not null]
  "trd_entrydatetime" text [not null]
  "trd_eventcode" text [not null]
  "trd_exceptiontype" text [not null]
  "trd_expirydate" text [not null]
}

Table "trd_event_narrative" {
  "trd_recordno" integer [not null]
  "trd_narrative_code" text [not null]
  "trd_seqno" text [not null]
  "trd_narrative" text [not null]
}

Table "trd_external_ref" {
  "trd_recordno" integer [not null]
  "ext_ref_extreftype" text [not null]
  "ext_ref_extref" text [not null]
}

Table "trd_inst_ext" {
  "trd_recordno" integer [not null]
  "trd_service" text [not null]
  "trd_extref" text [not null]
}

Table "trd_instruction" {
  "trd_recordno" integer [not null]
  "trd_procaction" text [not null]
  "trd_destination" text [not null]
  "trd_procstatus" text [not null]
  "trd_recordidentifier" text [not null]
  "trd_recordversion" text [not null]
  "trd_instformat" text [not null]
  "trd_tradeparty" text [not null]
  "trd_partyref" text [not null]
  "trd_deliverytype" text [not null]
  "trd_addresscode" text [not null]
  "trd_servicestatus" text [not null]
  "trd_noofcopies" text [not null]
  "trd_duedatetime" text [not null]
}

Table "trd_instruction_effect" {
  "trd_recordno" integer [not null]
  "trd_eventtype" text [not null]
  "trd_eventdate" text [not null]
  "trd_eventdateto" text [not null]
  "trd_entrydatetime" text [not null]
  "trd_eventcode" text [not null]
  "trd_exceptiontype" text [not null]
  "trd_expirydate" text [not null]
}

Table "trd_instrument" {
  "trd_recordno" integer [not null]
  "trd_instrtype" text [not null]
  "trd_p2000instrref" text [not null]
  "trd_instrreftype" text [not null]
  "trd_instrref" text [not null]
  "trd_longname" text [not null]
  "trd_quantity" text [not null]
}

Table "trd_journal" {
  "trd_recordno" integer [not null]
  "trd_accounts_company" text [not null]
  "trd_journal_type" text [not null]
  "trd_posting_type" text [not null]
  "trd_journal_no" text [not null]
  "trd_procaction" text [not null]
}

Table "trd_link" {
  "trd_recordno" integer [not null]
  "trd_link_type_wil" text [not null]
  "trd_main_record_no_wil" text [not null]
  "trd_sub_recordno_wil" text [not null]
  "trd_link_qty_wil" text [not null]
  "trd_link_status_wil" text [not null]
}

Table "trd_party" {
  "trd_recordno" integer [not null]
  "trd_trade_party" text [not null]
  "trd_partyref" text [not null]
  "trd_partyref_type_text" text [not null]
  "trd_ext_partyref" text [not null]
  "trd_longname" text [not null]
}

Table "trd_party_driver" {
  "trd_recordno" integer [not null]
  "trd_trade_party" text [not null]
  "trd_driver_type" text [not null]
  "trd_driver_code" text [not null]
}

Table "trd_processing" {
  "trd_recordno" integer [not null]
  "trd_proc_alias" text [not null]
  "trd_proc_action" text [not null]
  "trd_due_datetime" text [not null]
  "trd_done_datetime" text [not null]
}

Table "trd_processing_event" {
  "trd_recordno" integer [not null]
  "trd_eventtype" text [not null]
  "trd_eventdate" text [not null]
  "trd_eventdateto" text [not null]
  "trd_entrydatetime" text [not null]
  "trd_eventcode" text [not null]
  "trd_exceptiontype" text [not null]
  "trd_expirydate" text [not null]
}

Table "trd_rate" {
  "trd_recordno" integer [not null]
  "trd_charge_levy_type" text [not null]
  "trd_actual_charge" text [not null]
  "trd_amount_type" text [not null]
  "trd_rate_instrref_type" text [not null]
  "trd_rate_instrref" text [not null]
  "trd_rate_instrid" text [not null]
  "trd_rate_entered" text [not null]
  "trd_charge_rate" text [not null]
  "trd_mult_divind" text [not null]
}

Table "trd_ref_date" {
  "trd_recordno" integer [not null]
  "datetype" "character varying(4)" [not null]
  "datewil" date [not null]
  "refdatetime" "character varying(8)" [not null]
  "dateversionuser" "character varying(3)" [not null]
}

Table "trd_settlement" {
  "trd_recordno" integer [not null]
  "trd_deliverytype" text [not null]
  "trd_settleeventinstr" text [not null]
  "trd_settleterms" text [not null]
  "trd_originalqty" text [not null]
  "trd_openqty" text [not null]
  "trd_settledate" text [not null]
  "trd_delrecind" text [not null]
  "trd_settlestatus" text [not null]
  "trd_tradestatus" text [not null]
  "trd_settlenarrative1" text [not null]
  "trd_settlenarrative2" text [not null]
  "trd_settlenarrative3" text [not null]
  "trd_settlenarrative4" text [not null]
  "trd_settlenarrative5" text [not null]
  "trd_settlenarrative6" text [not null]
  "trd_settlenarrative7" text [not null]
  "trd_settlenarrative8" text [not null]
  "trd_dompaliaswil" text [not null]
  "trd_dompaliasdesc" text [not null]
  "trd_dompdepottypewil" text [not null]
  "trd_dompdaccwil" text [not null]
  "trd_dompservicewil" text [not null]
  "trd_secpaliaswil" text [not null]
  "trd_secpservicewil" text [not null]
}

Table "trd_trade" {
  "trd_uuid" uuid [not null, default: `gen_random_uuid()`]
  "trd_recordno" integer [not null]
  "trd_glosstraderef" integer [not null]
  "trd_versiono" integer [not null]
  "trd_origin" text [not null]
  "trd_tradetype" text [not null]
  "trd_settlementstatus" text [not null]
  "trd_tradestatus" "character varying(1)" [not null]
  "trd_originversion" integer [not null]
}

Table "trd_trade_code" {
  "trd_recordno" integer [not null]
  "trd_ext" text [not null]
  "trd_radeclass" text [not null]
  "trd_radecode" text [not null]
}

Table "trd_trade_narrative" {
  "trd_recordno" integer [not null]
  "trd_narrative_code" text [not null]
  "trd_seqno" text [not null]
  "trd_narrative" text [not null]
}

Table "users" {
  "username" "character varying" [not null]
  "hashed_password" "character varying" [not null]
  "full_name" "character varying" [not null]
  "email" "character varying" [not null]
  "password_changed_at" timestamp [not null, default: `now()`]
  "created_at" timestamp [not null, default: `now()`]
}
